import { randomUUID } from "node:crypto";
import { lstat, mkdir, readFile, realpath, rename, rm, writeFile, } from "node:fs/promises";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { isSafeProjectPath } from "../project/manifest.mjs";
export const GENERATED_MARKER = "# Generated by";
export const DOTENV_EXPAND_MARKER = "# Appelent dotenv-expand escaping: enabled";
/** Reject symlink destinations/ancestors and paths outside the canonical root. */
export async function assertSafeProjectPath(root, path) {
    if (!isSafeProjectPath(path) || path === ".")
        throw new Error("Unsafe project path");
    const canonicalRoot = await realpath(root);
    const full = resolve(root, path);
    const lexical = relative(resolve(root), full);
    if (!lexical ||
        lexical === ".." ||
        lexical.startsWith(`..${sep}`) ||
        isAbsolute(lexical))
        throw new Error("Unsafe project path");
    let current = resolve(root);
    for (const part of lexical.split(sep)) {
        current = join(current, part);
        try {
            if ((await lstat(current)).isSymbolicLink())
                throw new Error("Symlink project paths are unsupported");
            const actual = relative(canonicalRoot, await realpath(current));
            if (actual === ".." ||
                actual.startsWith(`..${sep}`) ||
                isAbsolute(actual))
                throw new Error("Unsafe project path");
        }
        catch (error) {
            if (error.code !== "ENOENT")
                throw error;
        }
    }
}
export function parseEnvText(text) {
    const values = Object.create(null);
    const lines = text.split(/\r?\n/);
    const expandEscaped = lines.includes(DOTENV_EXPAND_MARKER);
    for (let index = 0; index < lines.length; index += 1) {
        const line = (lines[index] ?? "").trim();
        if (!line || line.startsWith("#"))
            continue;
        const match = /^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/.exec(line);
        if (!match)
            throw new Error("Invalid dotenv assignment");
        const name = match[1] ?? "";
        if (Object.hasOwn(values, name))
            throw new Error("Duplicate dotenv assignment");
        let raw = match[2] ?? "";
        const quote = raw[0];
        if (quote === '"' || quote === "'" || quote === "`") {
            while (!(raw.length > 1 && raw.endsWith(quote)) &&
                index + 1 < lines.length)
                raw += `\n${lines[++index]}`;
            if (raw.length < 2 || !raw.endsWith(quote))
                throw new Error("Unterminated dotenv value");
            // Accept old engine JSON-escaped double quotes, while preserving literal multiline output.
            if (quote === '"' && !raw.includes("\n")) {
                try {
                    values[name] = JSON.parse(raw);
                }
                catch {
                    values[name] = raw
                        .slice(1, -1)
                        .replace(/\\n/g, "\n")
                        .replace(/\\r/g, "\r");
                }
            }
            else
                values[name] = raw.slice(1, -1);
        }
        else
            values[name] = (raw.split("#", 1)[0] ?? "").trim();
    }
    if (expandEscaped)
        for (const name of Object.keys(values))
            values[name] = (values[name] ?? "").replace(/\\\$/g, "$");
    return values;
}
function quote(value) {
    if (/^[A-Za-z0-9_./:@%+,-]+$/.test(value))
        return value;
    // Single/backtick quoted literal values survive dotenv consumers without JSON escaping.
    if (!value.includes("'"))
        return `'${value}'`;
    if (!value.includes("`"))
        return `\`${value}\``;
    if (!value.includes('"') && !value.includes("\\n") && !value.includes("\\r"))
        return `"${value}"`;
    throw new Error("Value cannot be represented losslessly in supported dotenv syntax");
}
export function renderGeneratedEnv(command, values, options = {}) {
    return [
        `${GENERATED_MARKER} ${command} — do not edit by hand.`,
        ...(options.expand ? [DOTENV_EXPAND_MARKER] : []),
        "# Edit the canonical source, then apply again.",
        "",
        ...Object.entries(values).map(([name, value]) => `${name}=${quote(options.expand ? value.replace(/\$/g, "\\$") : value)}`),
        "",
    ].join("\n");
}
export async function readOwnedFile(root, path) {
    await assertSafeProjectPath(root, path);
    try {
        const text = await readFile(join(root, path), "utf8");
        const owned = text.startsWith("# Generated by @appelent/dev env apply ") ||
            text.startsWith("# Generated by `pnpm run env:apply ");
        return {
            exists: true,
            owned,
            text,
            values: owned ? parseEnvText(text) : Object.create(null),
        };
    }
    catch (error) {
        if (error.code === "ENOENT")
            return {
                exists: false,
                owned: true,
                text: "",
                values: Object.create(null),
            };
        throw error;
    }
}
export async function atomicWrite(root, path, contents) {
    await assertSafeProjectPath(root, path);
    const full = join(root, path);
    await mkdir(dirname(full), { recursive: true });
    const temporary = join(dirname(full), `.${randomUUID()}.appelent.tmp`);
    try {
        await writeFile(temporary, contents, {
            encoding: "utf8",
            flag: "wx",
            mode: 0o600,
        });
        await rename(temporary, full);
    }
    finally {
        await rm(temporary, { force: true }).catch(() => undefined);
    }
}
