import type { FoodCategory, ServingBasis } from "./types";

/**
 * THE PROMOTION OVERLAY — the hand-authored half of the shipped food library.
 *
 * NEVO gives us 2,328 rows of accurate figures under identification strings
 * like "Mutton >10g fat raw av", and no portion data whatsoever. This file is
 * everything NEVO does not give us: a conversational name in both languages, an
 * emoji, one of the ten categories, search aliases, and the servings people
 * actually use. A food listed here is *promoted* — it comes back from ordinary
 * search. Everything else stays reachable through "search all".
 *
 * Rules this file follows (spec #68):
 *
 *   1. NEVO's own values and names are never amended — we only add. The licence
 *      permits additions "provided that it is clear these are additional to the
 *      original dataset"; that is what the overlay/extract split is for.
 *   2. Names describe the food as eaten. Size words belong in servings, not in
 *      names: "Banana", not "Large banana".
 *   3. Dry and cooked are separate entries wherever the difference is
 *      nutritionally large enough to matter (pasta, rice).
 *   4. At most three servings each. A picker longer than that stops being a
 *      shortcut.
 *   5. **Every NEVO beverage is per 100 GRAMS**, including water, beer and
 *      juice. So a volume-labelled serving must carry `ml` and a `basis` saying
 *      how the volume became a mass. `one-to-one` is the documented 1 ml ≈ 1 g
 *      fallback and is only used for water-like drinks; anything with sugar,
 *      fat or alcohol in it gets `density` and a note naming the figure used.
 *      A beverage without a practical serving cannot be promoted at all —
 *      generation fails.
 *
 * Serving amounts are everyday Dutch portions: a slice of bread is 35 g, a
 * beschuit is 11 g, a scoop of ice cream is 50 g, a boterham gets 7 g of
 * butter and 15 g of peanut butter. They are honest approximations of ordinary
 * use, not legal serving sizes.
 *
 * To add a food: find its NEVO code in `data/nevo/NEVO2025_v9.0.csv`, add an
 * entry here, and run `pnpm --filter @workouts/core generate:foods`.
 */

export type OverlayServing = {
	/** Serving label, English. Include the household measure — "Glass (200 ml)". */
	en: string;
	/** Serving label, Dutch. */
	nl: string;
	/** Amount in the food's NEVO base unit. Almost always grams. */
	amount: number;
	/** The volume the label names, when the label names one. */
	ml?: number;
	/** How `ml` became `amount`. Required whenever `ml` is set. */
	basis?: ServingBasis;
	/** Why this amount — the density used, or which portion it reflects. */
	note?: string;
};

export type OverlayEntry = {
	/** NEVO code. Source identity; the `shipped:` id comes from the lockfile. */
	code: number;
	/** Conversational English name. */
	en: string;
	/** Conversational Dutch name. */
	nl: string;
	emoji: string;
	category: FoodCategory;
	/** Extra English search terms. NEVO has no English synonyms at all. */
	aliasEn?: string[];
	/** Extra Dutch search terms, on top of NEVO's own `Synoniem` column. */
	aliasNl?: string[];
	servings: OverlayServing[];
};

// Densities used below, all standard food-composition figures:
//   milk & buttermilk 1.03, chocolate milk 1.04, fruit juice 1.04–1.05,
//   sugared soft drinks 1.03–1.04, beer 1.01, wine 0.99, vegetable oil 0.92.
// Water, black coffee, tea and sugar-free soft drinks use the documented
// 1 ml ≈ 1 g fallback.

export const PROMOTION_OVERLAY: OverlayEntry[] = [
	// ---------------------------------------------------------------- fruit --
	{
		code: 151,
		en: "Banana",
		nl: "Banaan",
		emoji: "🍌",
		category: "fruit",
		servings: [
			{
				en: "Banana (medium)",
				nl: "Banaan (middel)",
				amount: 120,
				note: "peeled",
			},
			{
				en: "Banana (large)",
				nl: "Banaan (groot)",
				amount: 150,
				note: "peeled",
			},
		],
	},
	{
		code: 875,
		en: "Apple",
		nl: "Appel",
		emoji: "🍎",
		category: "fruit",
		aliasEn: ["apple with skin"],
		servings: [
			{ en: "Apple", nl: "Appel", amount: 130 },
			{ en: "Half an apple", nl: "Halve appel", amount: 65 },
		],
	},
	{
		code: 171,
		en: "Orange",
		nl: "Sinaasappel",
		emoji: "🍊",
		category: "fruit",
		servings: [
			{ en: "Orange", nl: "Sinaasappel", amount: 140, note: "peeled" },
		],
	},
	{
		code: 148,
		en: "Strawberries",
		nl: "Aardbeien",
		emoji: "🍓",
		category: "fruit",
		servings: [
			{ en: "Handful", nl: "Handje", amount: 80 },
			{ en: "Bowl", nl: "Schaaltje", amount: 150 },
		],
	},
	{
		code: 152,
		en: "Blueberries",
		nl: "Blauwe bessen",
		emoji: "🫐",
		category: "fruit",
		servings: [
			{ en: "Handful", nl: "Handje", amount: 40 },
			{ en: "Punnet", nl: "Bakje", amount: 125 },
		],
	},
	{
		code: 2748,
		en: "Pear",
		nl: "Peer",
		emoji: "🍐",
		category: "fruit",
		servings: [{ en: "Pear", nl: "Peer", amount: 150 }],
	},
	{
		code: 1056,
		en: "Kiwi",
		nl: "Kiwi",
		emoji: "🥝",
		category: "fruit",
		servings: [{ en: "Kiwi", nl: "Kiwi", amount: 75, note: "peeled" }],
	},
	{
		code: 150,
		en: "Pineapple",
		nl: "Ananas",
		emoji: "🍍",
		category: "fruit",
		servings: [
			{ en: "Slice", nl: "Schijf", amount: 80 },
			{ en: "Bowl", nl: "Schaaltje", amount: 150 },
		],
	},
	{
		code: 692,
		en: "Mango",
		nl: "Mango",
		emoji: "🥭",
		category: "fruit",
		servings: [
			{ en: "Half a mango", nl: "Halve mango", amount: 100 },
			{ en: "Mango", nl: "Mango", amount: 200 },
		],
	},
	{
		code: 2750,
		en: "Grapes",
		nl: "Druiven",
		emoji: "🍇",
		category: "fruit",
		aliasEn: ["white grapes", "green grapes"],
		aliasNl: ["witte druiven"],
		servings: [
			{ en: "Handful", nl: "Handje", amount: 80 },
			{ en: "Bunch", nl: "Trosje", amount: 150 },
		],
	},
	{
		code: 1105,
		en: "Watermelon",
		nl: "Watermeloen",
		emoji: "🍉",
		category: "fruit",
		servings: [{ en: "Wedge", nl: "Punt", amount: 200, note: "without rind" }],
	},
	{
		code: 169,
		en: "Peach",
		nl: "Perzik",
		emoji: "🍑",
		category: "fruit",
		servings: [{ en: "Peach", nl: "Perzik", amount: 120 }],
	},
	{
		code: 163,
		en: "Cherries",
		nl: "Kersen",
		emoji: "🍒",
		category: "fruit",
		servings: [
			{ en: "Handful", nl: "Handje", amount: 80, note: "without stones" },
		],
	},
	{
		code: 158,
		en: "Lemon",
		nl: "Citroen",
		emoji: "🍋",
		category: "fruit",
		servings: [
			{ en: "Wedge", nl: "Partje", amount: 10 },
			{ en: "Half a lemon", nl: "Halve citroen", amount: 30 },
		],
	},
	{
		code: 33,
		en: "Raisins",
		nl: "Rozijnen",
		emoji: "🍇",
		category: "fruit",
		aliasEn: ["sultanas"],
		servings: [
			{ en: "Small box", nl: "Doosje", amount: 25 },
			{ en: "Handful", nl: "Handje", amount: 30 },
		],
	},
	{
		code: 179,
		en: "Apple sauce",
		nl: "Appelmoes",
		emoji: "🍎",
		category: "fruit",
		aliasNl: ["appelcompote"],
		servings: [{ en: "Portion", nl: "Portie", amount: 100 }],
	},

	// ----------------------------------------------------------- vegetables --
	{
		code: 982,
		en: "Boiled potatoes",
		nl: "Gekookte aardappelen",
		emoji: "🥔",
		category: "vegetables",
		aliasEn: ["potato"],
		aliasNl: ["aardappel"],
		servings: [
			{ en: "Potato", nl: "Aardappel", amount: 75 },
			{ en: "Portion", nl: "Portie", amount: 200 },
		],
	},
	{
		code: 1457,
		en: "Fried potatoes",
		nl: "Gebakken aardappelen",
		emoji: "🥔",
		category: "vegetables",
		servings: [{ en: "Portion", nl: "Portie", amount: 150 }],
	},
	{
		code: 1679,
		en: "Oven fries",
		nl: "Ovenfriet",
		emoji: "🍟",
		category: "vegetables",
		aliasEn: ["chips", "oven chips"],
		aliasNl: ["patat uit de oven", "ovenfrites"],
		servings: [{ en: "Portion", nl: "Portie", amount: 150 }],
	},
	{
		code: 2112,
		en: "Sweet potato (boiled)",
		nl: "Zoete aardappel (gekookt)",
		emoji: "🍠",
		category: "vegetables",
		servings: [{ en: "Portion", nl: "Portie", amount: 150 }],
	},
	{
		code: 60,
		en: "Tomato",
		nl: "Tomaat",
		emoji: "🍅",
		category: "vegetables",
		servings: [
			{ en: "Tomato", nl: "Tomaat", amount: 90 },
			{
				en: "Handful of cherry tomatoes",
				nl: "Handje cherrytomaatjes",
				amount: 100,
			},
		],
	},
	{
		code: 2739,
		en: "Cucumber",
		nl: "Komkommer",
		emoji: "🥒",
		category: "vegetables",
		servings: [
			{ en: "Slices", nl: "Plakjes", amount: 50 },
			{ en: "Quarter cucumber", nl: "Kwart komkommer", amount: 100 },
		],
	},
	{
		code: 71,
		en: "Carrot",
		nl: "Wortel",
		emoji: "🥕",
		category: "vegetables",
		aliasNl: ["worteltjes", "peen"],
		servings: [
			{ en: "Carrot", nl: "Wortel", amount: 70 },
			{ en: "Portion", nl: "Portie", amount: 150 },
		],
	},
	{
		code: 920,
		en: "Broccoli (boiled)",
		nl: "Broccoli (gekookt)",
		emoji: "🥦",
		category: "vegetables",
		servings: [{ en: "Portion", nl: "Portie", amount: 150 }],
	},
	{
		code: 15,
		en: "Cauliflower (boiled)",
		nl: "Bloemkool (gekookt)",
		emoji: "🥬",
		category: "vegetables",
		servings: [{ en: "Portion", nl: "Portie", amount: 150 }],
	},
	{
		code: 52,
		en: "Spinach (boiled)",
		nl: "Spinazie (gekookt)",
		emoji: "🥬",
		category: "vegetables",
		servings: [{ en: "Portion", nl: "Portie", amount: 150 }],
	},
	{
		code: 63,
		en: "Onion",
		nl: "Ui",
		emoji: "🧅",
		category: "vegetables",
		servings: [
			{ en: "Half an onion", nl: "Halve ui", amount: 50 },
			{ en: "Onion", nl: "Ui", amount: 100 },
		],
	},
	{
		code: 884,
		en: "Red bell pepper",
		nl: "Rode paprika",
		emoji: "🫑",
		category: "vegetables",
		aliasEn: ["red pepper", "capsicum"],
		servings: [
			{ en: "Half a pepper", nl: "Halve paprika", amount: 75 },
			{ en: "Bell pepper", nl: "Paprika", amount: 150 },
		],
	},
	{
		code: 19,
		en: "Mushrooms",
		nl: "Champignons",
		emoji: "🍄",
		category: "vegetables",
		servings: [
			{ en: "Handful", nl: "Handje", amount: 80 },
			{ en: "Punnet", nl: "Bakje", amount: 250 },
		],
	},
	{
		code: 951,
		en: "Green beans (boiled)",
		nl: "Sperziebonen (gekookt)",
		emoji: "🫛",
		category: "vegetables",
		aliasEn: ["french beans", "haricots verts"],
		servings: [{ en: "Portion", nl: "Portie", amount: 150 }],
	},
	{
		code: 953,
		en: "Peas",
		nl: "Doperwten",
		emoji: "🫛",
		category: "vegetables",
		servings: [{ en: "Portion", nl: "Portie", amount: 100 }],
	},
	{
		code: 67,
		en: "Chicory",
		nl: "Witlof",
		emoji: "🥬",
		category: "vegetables",
		aliasEn: ["belgian endive"],
		servings: [{ en: "Head", nl: "Stronkje", amount: 90 }],
	},
	{
		code: 46,
		en: "Lettuce",
		nl: "Kropsla",
		emoji: "🥬",
		category: "vegetables",
		aliasEn: ["butterhead lettuce", "salad"],
		aliasNl: ["sla"],
		servings: [{ en: "Portion", nl: "Portie", amount: 50 }],
	},
	{
		code: 42,
		en: "Red cabbage (boiled)",
		nl: "Rode kool (gekookt)",
		emoji: "🥬",
		category: "vegetables",
		servings: [{ en: "Portion", nl: "Portie", amount: 150 }],
	},
	{
		code: 73,
		en: "Sauerkraut",
		nl: "Zuurkool",
		emoji: "🥬",
		category: "vegetables",
		servings: [{ en: "Portion", nl: "Portie", amount: 200 }],
	},
	{
		code: 922,
		en: "Courgette",
		nl: "Courgette",
		emoji: "🥒",
		category: "vegetables",
		aliasEn: ["zucchini"],
		servings: [{ en: "Half a courgette", nl: "Halve courgette", amount: 150 }],
	},
	{
		code: 689,
		en: "Avocado",
		nl: "Avocado",
		emoji: "🥑",
		category: "vegetables",
		servings: [
			{ en: "Half an avocado", nl: "Halve avocado", amount: 100 },
			{ en: "Avocado", nl: "Avocado", amount: 200 },
		],
	},
	{
		code: 958,
		en: "Beetroot (boiled)",
		nl: "Rode biet (gekookt)",
		emoji: "🥬",
		category: "vegetables",
		aliasNl: ["kroten"],
		servings: [{ en: "Portion", nl: "Portie", amount: 100 }],
	},
	{
		code: 562,
		en: "Leek",
		nl: "Prei",
		emoji: "🥬",
		category: "vegetables",
		servings: [{ en: "Leek", nl: "Prei", amount: 150 }],
	},

	// --------------------------------------------------------------- grains --
	{
		code: 236,
		en: "Brown bread",
		nl: "Bruinbrood",
		emoji: "🍞",
		category: "grains",
		aliasEn: ["bread"],
		aliasNl: ["boterham", "brood"],
		servings: [
			{ en: "Slice", nl: "Boterham", amount: 35 },
			{ en: "Two slices", nl: "Twee boterhammen", amount: 70 },
		],
	},
	{
		code: 246,
		en: "Wholemeal bread",
		nl: "Volkorenbrood",
		emoji: "🍞",
		category: "grains",
		aliasEn: ["whole wheat bread"],
		aliasNl: ["boterham volkoren"],
		servings: [
			{ en: "Slice", nl: "Boterham", amount: 35 },
			{ en: "Two slices", nl: "Twee boterhammen", amount: 70 },
		],
	},
	{
		code: 248,
		en: "White bread",
		nl: "Witbrood",
		emoji: "🍞",
		category: "grains",
		servings: [
			{ en: "Slice", nl: "Boterham", amount: 35 },
			{ en: "Two slices", nl: "Twee boterhammen", amount: 70 },
		],
	},
	{
		code: 242,
		en: "Rye bread",
		nl: "Roggebrood",
		emoji: "🍞",
		category: "grains",
		servings: [{ en: "Slice", nl: "Plak", amount: 25 }],
	},
	{
		code: 233,
		en: "Currant bread",
		nl: "Krentenbrood",
		emoji: "🍞",
		category: "grains",
		servings: [{ en: "Slice", nl: "Boterham", amount: 35 }],
	},
	{
		code: 1361,
		en: "Turkish bread",
		nl: "Turks brood",
		emoji: "🥖",
		category: "grains",
		aliasNl: ["pide"],
		servings: [{ en: "Piece", nl: "Stuk", amount: 75 }],
	},
	{
		code: 227,
		en: "Rusk",
		nl: "Beschuit",
		emoji: "🍘",
		category: "grains",
		servings: [
			{ en: "Rusk", nl: "Beschuit", amount: 11 },
			{ en: "Two rusks", nl: "Twee beschuiten", amount: 22 },
		],
	},
	{
		code: 229,
		en: "Crispbread",
		nl: "Knäckebröd",
		emoji: "🍘",
		category: "grains",
		aliasNl: ["knackebrod", "cracker"],
		servings: [{ en: "Slice", nl: "Plak", amount: 10 }],
	},
	{
		code: 4,
		en: "Pasta (dry)",
		nl: "Pasta (ongekookt)",
		emoji: "🍝",
		category: "grains",
		aliasEn: ["spaghetti", "macaroni", "penne"],
		aliasNl: ["spaghetti ongekookt"],
		servings: [{ en: "Portion (dry)", nl: "Portie (ongekookt)", amount: 75 }],
	},
	{
		code: 659,
		en: "Pasta (cooked)",
		nl: "Pasta (gekookt)",
		emoji: "🍝",
		category: "grains",
		aliasEn: ["spaghetti", "macaroni", "penne"],
		servings: [{ en: "Portion", nl: "Portie", amount: 200 }],
	},
	{
		code: 2157,
		en: "Wholemeal pasta (cooked)",
		nl: "Volkorenpasta (gekookt)",
		emoji: "🍝",
		category: "grains",
		servings: [{ en: "Portion", nl: "Portie", amount: 200 }],
	},
	{
		code: 5,
		en: "Rice (dry)",
		nl: "Rijst (ongekookt)",
		emoji: "🍚",
		category: "grains",
		servings: [{ en: "Portion (dry)", nl: "Portie (ongekookt)", amount: 75 }],
	},
	{
		code: 658,
		en: "Rice (cooked)",
		nl: "Rijst (gekookt)",
		emoji: "🍚",
		category: "grains",
		aliasEn: ["white rice"],
		aliasNl: ["witte rijst"],
		servings: [{ en: "Portion", nl: "Portie", amount: 200 }],
	},
	{
		code: 213,
		en: "Oats",
		nl: "Havermout",
		emoji: "🥣",
		category: "grains",
		aliasEn: ["oatmeal", "rolled oats", "porridge oats"],
		servings: [
			{ en: "Portion", nl: "Portie", amount: 40 },
			{ en: "Large portion", nl: "Grote portie", amount: 60 },
		],
	},
	{
		code: 2081,
		en: "Cornflakes",
		nl: "Cornflakes",
		emoji: "🥣",
		category: "grains",
		aliasEn: ["breakfast cereal"],
		aliasNl: ["ontbijtgranen"],
		servings: [{ en: "Portion", nl: "Portie", amount: 30 }],
	},
	{
		code: 3154,
		en: "Quinoa (cooked)",
		nl: "Quinoa (gekookt)",
		emoji: "🍚",
		category: "grains",
		servings: [{ en: "Portion", nl: "Portie", amount: 150 }],
	},
	{
		code: 2158,
		en: "Couscous (cooked)",
		nl: "Couscous (gekookt)",
		emoji: "🍚",
		category: "grains",
		servings: [{ en: "Portion", nl: "Portie", amount: 150 }],
	},
	{
		code: 3200,
		en: "Bulgur (cooked)",
		nl: "Bulgur (gekookt)",
		emoji: "🍚",
		category: "grains",
		servings: [{ en: "Portion", nl: "Portie", amount: 150 }],
	},
	{
		code: 467,
		en: "Pancake",
		nl: "Pannenkoek",
		emoji: "🥞",
		category: "grains",
		servings: [{ en: "Pancake", nl: "Pannenkoek", amount: 90 }],
	},

	// -------------------------------------------------------------- protein --
	{
		code: 1634,
		en: "Chicken breast (raw)",
		nl: "Kipfilet (rauw)",
		emoji: "🍗",
		category: "protein",
		servings: [{ en: "Fillet", nl: "Filet", amount: 120 }],
	},
	{
		code: 1392,
		en: "Chicken breast (cooked)",
		nl: "Kipfilet (bereid)",
		emoji: "🍗",
		category: "protein",
		aliasEn: ["chicken"],
		aliasNl: ["kip"],
		servings: [{ en: "Fillet", nl: "Filet", amount: 100 }],
	},
	{
		code: 2654,
		en: "Sliced chicken breast",
		nl: "Kipfilet (vleeswaar)",
		emoji: "🍗",
		category: "protein",
		aliasEn: ["chicken cold cut"],
		servings: [{ en: "Slice", nl: "Plakje", amount: 15 }],
	},
	{
		code: 1405,
		en: "Minced beef (raw)",
		nl: "Rundergehakt (rauw)",
		emoji: "🥩",
		category: "protein",
		servings: [{ en: "Portion", nl: "Portie", amount: 100 }],
	},
	{
		code: 1540,
		en: "Minced beef (fried)",
		nl: "Rundergehakt (rul gebakken)",
		emoji: "🥩",
		category: "protein",
		servings: [{ en: "Portion", nl: "Portie", amount: 75 }],
	},
	{
		code: 1536,
		en: "Steak",
		nl: "Biefstuk",
		emoji: "🥩",
		category: "protein",
		servings: [{ en: "Steak", nl: "Biefstuk", amount: 100 }],
	},
	{
		code: 1569,
		en: "Beef burger",
		nl: "Hamburger",
		emoji: "🍔",
		category: "protein",
		servings: [{ en: "Burger", nl: "Hamburger", amount: 80 }],
	},
	{
		code: 324,
		en: "Smoked sausage",
		nl: "Rookworst",
		emoji: "🌭",
		category: "protein",
		servings: [
			{ en: "Portion", nl: "Portie", amount: 75 },
			{ en: "Whole sausage", nl: "Hele worst", amount: 250 },
		],
	},
	{
		code: 784,
		en: "Ham",
		nl: "Achterham",
		emoji: "🍖",
		category: "protein",
		aliasNl: ["ham"],
		servings: [{ en: "Slice", nl: "Plakje", amount: 15 }],
	},
	{
		code: 3345,
		en: "Roast beef",
		nl: "Rosbief",
		emoji: "🍖",
		category: "protein",
		servings: [{ en: "Slice", nl: "Plakje", amount: 15 }],
	},
	{
		code: 84,
		en: "Boiled egg",
		nl: "Gekookt ei",
		emoji: "🥚",
		category: "protein",
		aliasEn: ["egg"],
		aliasNl: ["ei"],
		servings: [
			{ en: "Egg", nl: "Ei", amount: 50 },
			{ en: "Two eggs", nl: "Twee eieren", amount: 100 },
		],
	},
	{
		code: 1314,
		en: "Fried egg",
		nl: "Gebakken ei",
		emoji: "🍳",
		category: "protein",
		aliasNl: ["spiegelei"],
		servings: [{ en: "Egg", nl: "Ei", amount: 46 }],
	},
	{
		code: 83,
		en: "Egg (raw)",
		nl: "Ei (rauw)",
		emoji: "🥚",
		category: "protein",
		servings: [{ en: "Egg", nl: "Ei", amount: 50 }],
	},
	{
		code: 1587,
		en: "Salmon (raw)",
		nl: "Zalm (rauw)",
		emoji: "🐟",
		category: "protein",
		servings: [{ en: "Fillet", nl: "Moot", amount: 125 }],
	},
	{
		code: 1096,
		en: "Smoked salmon",
		nl: "Gerookte zalm",
		emoji: "🐟",
		category: "protein",
		servings: [{ en: "Portion", nl: "Portie", amount: 50 }],
	},
	{
		code: 1590,
		en: "Tuna in water (tinned)",
		nl: "Tonijn in water (blik)",
		emoji: "🐟",
		category: "protein",
		aliasEn: ["tuna"],
		servings: [{ en: "Tin (drained)", nl: "Blikje (uitgelekt)", amount: 145 }],
	},
	{
		code: 1315,
		en: "Cod fillet (fried)",
		nl: "Kabeljauwfilet (gebakken)",
		emoji: "🐟",
		category: "protein",
		servings: [{ en: "Fillet", nl: "Filet", amount: 125 }],
	},
	{
		code: 350,
		en: "Salted herring",
		nl: "Haring",
		emoji: "🐟",
		category: "protein",
		aliasEn: ["herring", "maatjes"],
		servings: [{ en: "Herring", nl: "Haring", amount: 100 }],
	},
	{
		code: 348,
		en: "Shrimps",
		nl: "Hollandse garnalen",
		emoji: "🦐",
		category: "protein",
		aliasNl: ["garnalen"],
		servings: [{ en: "Portion", nl: "Portie", amount: 75 }],
	},
	{
		code: 660,
		en: "Brown beans (tin)",
		nl: "Bruine bonen (blik)",
		emoji: "🫘",
		category: "protein",
		servings: [{ en: "Portion", nl: "Portie", amount: 200 }],
	},
	{
		code: 3184,
		en: "Kidney beans (tin)",
		nl: "Kidneybonen (blik)",
		emoji: "🫘",
		category: "protein",
		servings: [{ en: "Portion", nl: "Portie", amount: 150 }],
	},
	{
		code: 970,
		en: "Lentils (cooked)",
		nl: "Linzen (gekookt)",
		emoji: "🫘",
		category: "protein",
		servings: [{ en: "Portion", nl: "Portie", amount: 150 }],
	},
	{
		code: 1095,
		en: "Chickpeas (cooked)",
		nl: "Kikkererwten (gekookt)",
		emoji: "🫘",
		category: "protein",
		servings: [{ en: "Portion", nl: "Portie", amount: 150 }],
	},
	{
		code: 204,
		en: "Peanuts",
		nl: "Pinda's",
		emoji: "🥜",
		category: "protein",
		servings: [{ en: "Handful", nl: "Handje", amount: 25 }],
	},
	{
		code: 198,
		en: "Almonds",
		nl: "Amandelen",
		emoji: "🌰",
		category: "protein",
		servings: [{ en: "Handful", nl: "Handje", amount: 25 }],
	},
	{
		code: 206,
		en: "Walnuts",
		nl: "Walnoten",
		emoji: "🌰",
		category: "protein",
		servings: [{ en: "Handful", nl: "Handje", amount: 25 }],
	},
	{
		code: 199,
		en: "Cashew nuts",
		nl: "Cashewnoten",
		emoji: "🥜",
		category: "protein",
		servings: [{ en: "Handful", nl: "Handje", amount: 25 }],
	},
	{
		code: 5519,
		en: "Tofu",
		nl: "Tofu",
		emoji: "🧆",
		category: "protein",
		aliasNl: ["tahoe"],
		servings: [{ en: "Portion", nl: "Portie", amount: 100 }],
	},
	{
		code: 5573,
		en: "Tempeh",
		nl: "Tempeh",
		emoji: "🧆",
		category: "protein",
		servings: [{ en: "Portion", nl: "Portie", amount: 100 }],
	},

	// ---------------------------------------------------------------- dairy --
	// Milk is per 100 g like every other NEVO beverage, so a glass stores a
	// mass: 200 ml × 1.03 g/ml ≈ 206 g.
	{
		code: 286,
		en: "Semi-skimmed milk",
		nl: "Halfvolle melk",
		emoji: "🥛",
		category: "dairy",
		aliasEn: ["milk"],
		aliasNl: ["melk"],
		servings: [
			{
				en: "Glass (200 ml)",
				nl: "Glas (200 ml)",
				amount: 206,
				ml: 200,
				basis: "density",
				note: "milk 1.03 g/ml",
			},
			{
				en: "Mug (250 ml)",
				nl: "Beker (250 ml)",
				amount: 258,
				ml: 250,
				basis: "density",
				note: "milk 1.03 g/ml",
			},
		],
	},
	{
		code: 279,
		en: "Whole milk",
		nl: "Volle melk",
		emoji: "🥛",
		category: "dairy",
		servings: [
			{
				en: "Glass (200 ml)",
				nl: "Glas (200 ml)",
				amount: 206,
				ml: 200,
				basis: "density",
				note: "milk 1.03 g/ml",
			},
		],
	},
	{
		code: 294,
		en: "Skimmed milk",
		nl: "Magere melk",
		emoji: "🥛",
		category: "dairy",
		servings: [
			{
				en: "Glass (200 ml)",
				nl: "Glas (200 ml)",
				amount: 207,
				ml: 200,
				basis: "density",
				note: "skimmed milk 1.035 g/ml",
			},
		],
	},
	{
		code: 289,
		en: "Buttermilk",
		nl: "Karnemelk",
		emoji: "🥛",
		category: "dairy",
		servings: [
			{
				en: "Glass (200 ml)",
				nl: "Glas (200 ml)",
				amount: 207,
				ml: 200,
				basis: "density",
				note: "buttermilk 1.035 g/ml",
			},
		],
	},
	{
		code: 272,
		en: "Chocolate milk",
		nl: "Chocolademelk",
		emoji: "🥛",
		category: "dairy",
		servings: [
			{
				en: "Glass (200 ml)",
				nl: "Glas (200 ml)",
				amount: 208,
				ml: 200,
				basis: "density",
				note: "chocolate milk 1.04 g/ml",
			},
			{
				en: "Carton (300 ml)",
				nl: "Pakje (300 ml)",
				amount: 312,
				ml: 300,
				basis: "density",
				note: "chocolate milk 1.04 g/ml",
			},
		],
	},
	{
		code: 280,
		en: "Coffee milk",
		nl: "Koffiemelk",
		emoji: "🥛",
		category: "dairy",
		servings: [{ en: "Cup portion", nl: "Cupje", amount: 10 }],
	},
	{
		code: 301,
		en: "Low-fat yoghurt",
		nl: "Magere yoghurt",
		emoji: "🥛",
		category: "dairy",
		aliasEn: ["yoghurt", "yogurt"],
		servings: [
			{ en: "Bowl", nl: "Schaaltje", amount: 150 },
			{ en: "Large bowl", nl: "Grote schaal", amount: 250 },
		],
	},
	{
		code: 278,
		en: "Full-fat yoghurt",
		nl: "Volle yoghurt",
		emoji: "🥛",
		category: "dairy",
		servings: [{ en: "Bowl", nl: "Schaaltje", amount: 150 }],
	},
	{
		code: 2503,
		en: "Greek yoghurt",
		nl: "Griekse yoghurt",
		emoji: "🥛",
		category: "dairy",
		servings: [{ en: "Bowl", nl: "Schaaltje", amount: 150 }],
	},
	{
		code: 305,
		en: "Low-fat quark",
		nl: "Magere kwark",
		emoji: "🥛",
		category: "dairy",
		aliasEn: ["quark", "skyr"],
		servings: [
			{ en: "Bowl", nl: "Schaaltje", amount: 150 },
			{ en: "Tub", nl: "Bakje", amount: 250 },
		],
	},
	{
		code: 307,
		en: "Full-fat quark",
		nl: "Volle kwark",
		emoji: "🥛",
		category: "dairy",
		servings: [{ en: "Bowl", nl: "Schaaltje", amount: 150 }],
	},
	{
		code: 513,
		en: "Gouda cheese 48+",
		nl: "Goudse kaas 48+",
		emoji: "🧀",
		category: "dairy",
		aliasEn: ["cheese"],
		aliasNl: ["kaas"],
		servings: [
			{ en: "Slice", nl: "Plak", amount: 20 },
			{ en: "Cubes", nl: "Blokjes", amount: 40 },
		],
	},
	{
		code: 1382,
		en: "Cheese 30+",
		nl: "Kaas 30+",
		emoji: "🧀",
		category: "dairy",
		aliasEn: ["light cheese"],
		aliasNl: ["magere kaas"],
		servings: [{ en: "Slice", nl: "Plak", amount: 20 }],
	},
	{
		code: 654,
		en: "Cottage cheese",
		nl: "Hüttenkäse",
		emoji: "🧀",
		category: "dairy",
		aliasNl: ["huttenkase"],
		servings: [{ en: "Portion", nl: "Portie", amount: 100 }],
	},
	{
		code: 1955,
		en: "Mozzarella",
		nl: "Mozzarella",
		emoji: "🧀",
		category: "dairy",
		servings: [
			{ en: "Ball", nl: "Bol", amount: 125 },
			{ en: "Half a ball", nl: "Halve bol", amount: 62 },
		],
	},
	{
		code: 3362,
		en: "Feta",
		nl: "Feta",
		emoji: "🧀",
		category: "dairy",
		servings: [{ en: "Portion", nl: "Portie", amount: 30 }],
	},
	{
		code: 282,
		en: "Vanilla custard",
		nl: "Vanillevla",
		emoji: "🍮",
		category: "dairy",
		aliasEn: ["custard"],
		aliasNl: ["vla"],
		servings: [{ en: "Bowl", nl: "Schaaltje", amount: 150 }],
	},
	{
		code: 299,
		en: "Whipping cream",
		nl: "Slagroom",
		emoji: "🥛",
		category: "dairy",
		servings: [
			{ en: "Tablespoon", nl: "Eetlepel", amount: 15 },
			{ en: "Portion", nl: "Portie", amount: 50 },
		],
	},

	// ----------------------------------------------------------------- fats --
	{
		code: 879,
		en: "Butter (salted)",
		nl: "Gezouten roomboter",
		emoji: "🧈",
		category: "fats",
		aliasEn: ["butter"],
		aliasNl: ["boter"],
		servings: [
			{ en: "For a slice of bread", nl: "Op een boterham", amount: 7 },
			{ en: "Knob", nl: "Klontje", amount: 15 },
		],
	},
	{
		code: 310,
		en: "Butter (unsalted)",
		nl: "Ongezouten roomboter",
		emoji: "🧈",
		category: "fats",
		servings: [
			{ en: "For a slice of bread", nl: "Op een boterham", amount: 7 },
		],
	},
	{
		code: 2063,
		en: "Margarine",
		nl: "Margarine",
		emoji: "🧈",
		category: "fats",
		servings: [
			{ en: "For a slice of bread", nl: "Op een boterham", amount: 7 },
		],
	},
	{
		code: 2059,
		en: "Low-fat spread",
		nl: "Halvarine",
		emoji: "🧈",
		category: "fats",
		servings: [
			{ en: "For a slice of bread", nl: "Op een boterham", amount: 7 },
		],
	},
	{
		code: 601,
		en: "Olive oil",
		nl: "Olijfolie",
		emoji: "🫒",
		category: "fats",
		servings: [
			{
				en: "Tablespoon (15 ml)",
				nl: "Eetlepel (15 ml)",
				amount: 14,
				ml: 15,
				basis: "density",
				note: "olive oil 0.92 g/ml",
			},
			{
				en: "Teaspoon (5 ml)",
				nl: "Theelepel (5 ml)",
				amount: 5,
				ml: 5,
				basis: "density",
				note: "olive oil 0.92 g/ml",
			},
		],
	},
	{
		code: 317,
		en: "Sunflower oil",
		nl: "Zonnebloemolie",
		emoji: "🌻",
		category: "fats",
		servings: [
			{
				en: "Tablespoon (15 ml)",
				nl: "Eetlepel (15 ml)",
				amount: 14,
				ml: 15,
				basis: "density",
				note: "sunflower oil 0.92 g/ml",
			},
		],
	},
	{
		code: 451,
		en: "Mayonnaise",
		nl: "Mayonaise",
		emoji: "🥄",
		category: "fats",
		servings: [{ en: "Tablespoon", nl: "Eetlepel", amount: 15 }],
	},
	{
		code: 729,
		en: "Low-fat mayonnaise",
		nl: "Halvanaise",
		emoji: "🥄",
		category: "fats",
		servings: [{ en: "Tablespoon", nl: "Eetlepel", amount: 15 }],
	},

	// --------------------------------------------------------------- drinks --
	// Every one of these is per 100 g in NEVO. Water-like drinks take the
	// documented 1 ml ≈ 1 g fallback; everything with sugar, fat or alcohol in
	// it gets an explicit density.
	{
		code: 1885,
		en: "Tap water",
		nl: "Kraanwater",
		emoji: "💧",
		category: "drinks",
		aliasEn: ["water"],
		aliasNl: ["water"],
		servings: [
			{
				en: "Glass (200 ml)",
				nl: "Glas (200 ml)",
				amount: 200,
				ml: 200,
				basis: "one-to-one",
				note: "water-like: 1 ml ≈ 1 g",
			},
			{
				en: "Bottle (500 ml)",
				nl: "Fles (500 ml)",
				amount: 500,
				ml: 500,
				basis: "one-to-one",
				note: "water-like: 1 ml ≈ 1 g",
			},
		],
	},
	{
		code: 747,
		en: "Mineral water",
		nl: "Mineraalwater",
		emoji: "💧",
		category: "drinks",
		aliasEn: ["sparkling water", "still water"],
		aliasNl: ["spa", "bruisend water"],
		servings: [
			{
				en: "Glass (200 ml)",
				nl: "Glas (200 ml)",
				amount: 200,
				ml: 200,
				basis: "one-to-one",
				note: "water-like: 1 ml ≈ 1 g",
			},
			{
				en: "Bottle (500 ml)",
				nl: "Fles (500 ml)",
				amount: 500,
				ml: 500,
				basis: "one-to-one",
				note: "water-like: 1 ml ≈ 1 g",
			},
		],
	},
	{
		code: 644,
		en: "Coffee (black)",
		nl: "Koffie (zwart)",
		emoji: "☕",
		category: "drinks",
		aliasEn: ["coffee"],
		aliasNl: ["koffie"],
		servings: [
			{
				en: "Cup (125 ml)",
				nl: "Kopje (125 ml)",
				amount: 125,
				ml: 125,
				basis: "one-to-one",
				note: "water-like: brewed coffee is ~99% water",
			},
			{
				en: "Mug (250 ml)",
				nl: "Beker (250 ml)",
				amount: 250,
				ml: 250,
				basis: "one-to-one",
				note: "water-like: brewed coffee is ~99% water",
			},
		],
	},
	{
		code: 645,
		en: "Tea",
		nl: "Thee",
		emoji: "🍵",
		category: "drinks",
		servings: [
			{
				en: "Cup (150 ml)",
				nl: "Kopje (150 ml)",
				amount: 150,
				ml: 150,
				basis: "one-to-one",
				note: "water-like: brewed tea is ~99.7% water",
			},
		],
	},
	{
		code: 410,
		en: "Orange juice",
		nl: "Sinaasappelsap",
		emoji: "🧃",
		category: "drinks",
		aliasEn: ["juice"],
		aliasNl: ["jus d'orange", "sap"],
		servings: [
			{
				en: "Glass (200 ml)",
				nl: "Glas (200 ml)",
				amount: 208,
				ml: 200,
				basis: "density",
				note: "orange juice 1.04 g/ml",
			},
		],
	},
	{
		code: 2755,
		en: "Fresh orange juice",
		nl: "Vers geperst sinaasappelsap",
		emoji: "🍊",
		category: "drinks",
		servings: [
			{
				en: "Glass (200 ml)",
				nl: "Glas (200 ml)",
				amount: 208,
				ml: 200,
				basis: "density",
				note: "orange juice 1.04 g/ml",
			},
		],
	},
	{
		code: 383,
		en: "Apple juice",
		nl: "Appelsap",
		emoji: "🧃",
		category: "drinks",
		servings: [
			{
				en: "Glass (200 ml)",
				nl: "Glas (200 ml)",
				amount: 209,
				ml: 200,
				basis: "density",
				note: "apple juice 1.045 g/ml",
			},
		],
	},
	{
		code: 395,
		en: "Cola",
		nl: "Cola",
		emoji: "🥤",
		category: "drinks",
		aliasEn: ["soft drink", "soda"],
		aliasNl: ["frisdrank"],
		servings: [
			{
				en: "Glass (200 ml)",
				nl: "Glas (200 ml)",
				amount: 207,
				ml: 200,
				basis: "density",
				note: "sugared cola 1.037 g/ml",
			},
			{
				en: "Can (330 ml)",
				nl: "Blikje (330 ml)",
				amount: 342,
				ml: 330,
				basis: "density",
				note: "sugared cola 1.037 g/ml",
			},
		],
	},
	{
		code: 2086,
		en: "Ice tea",
		nl: "IJsthee",
		emoji: "🥤",
		category: "drinks",
		servings: [
			{
				en: "Glass (200 ml)",
				nl: "Glas (200 ml)",
				amount: 206,
				ml: 200,
				basis: "density",
				note: "sugared ice tea 1.03 g/ml",
			},
		],
	},
	{
		code: 2087,
		en: "Ice tea (light)",
		nl: "IJsthee light",
		emoji: "🥤",
		category: "drinks",
		servings: [
			{
				en: "Glass (200 ml)",
				nl: "Glas (200 ml)",
				amount: 200,
				ml: 200,
				basis: "one-to-one",
				note: "water-like: sweetened without sugar",
			},
		],
	},
	{
		code: 2041,
		en: "Sports drink (isotonic)",
		nl: "Sportdrank (isotoon)",
		emoji: "🥤",
		category: "drinks",
		aliasEn: ["sports drink"],
		aliasNl: ["sportdrank"],
		servings: [
			{
				en: "Bottle (500 ml)",
				nl: "Bidon (500 ml)",
				amount: 515,
				ml: 500,
				basis: "density",
				note: "isotonic sports drink 1.03 g/ml",
			},
		],
	},
	{
		code: 870,
		en: "Soy drink (unsweetened)",
		nl: "Sojadrink (ongezoet)",
		emoji: "🥛",
		category: "drinks",
		aliasEn: ["soy milk"],
		aliasNl: ["sojamelk"],
		servings: [
			{
				en: "Glass (200 ml)",
				nl: "Glas (200 ml)",
				amount: 206,
				ml: 200,
				basis: "density",
				note: "soy drink 1.03 g/ml",
			},
		],
	},
	{
		code: 390,
		en: "Beer (pilsner)",
		nl: "Bier (pils)",
		emoji: "🍺",
		category: "drinks",
		aliasEn: ["beer", "lager"],
		aliasNl: ["pils", "biertje"],
		servings: [
			{
				en: "Glass (250 ml)",
				nl: "Glas (250 ml)",
				amount: 253,
				ml: 250,
				basis: "density",
				note: "pilsner 1.01 g/ml",
			},
			{
				en: "Bottle (300 ml)",
				nl: "Flesje (300 ml)",
				amount: 303,
				ml: 300,
				basis: "density",
				note: "pilsner 1.01 g/ml",
			},
		],
	},
	{
		code: 1519,
		en: "Alcohol-free beer",
		nl: "Alcoholvrij bier",
		emoji: "🍺",
		category: "drinks",
		servings: [
			{
				en: "Glass (250 ml)",
				nl: "Glas (250 ml)",
				amount: 255,
				ml: 250,
				basis: "density",
				note: "alcohol-free beer 1.02 g/ml — more residual sugar than pilsner",
			},
		],
	},
	{
		code: 422,
		en: "Red wine",
		nl: "Rode wijn",
		emoji: "🍷",
		category: "drinks",
		aliasEn: ["wine"],
		aliasNl: ["wijn"],
		servings: [
			{
				en: "Glass (150 ml)",
				nl: "Glas (150 ml)",
				amount: 148,
				ml: 150,
				basis: "density",
				note: "wine 0.99 g/ml — alcohol is lighter than water",
			},
		],
	},
	{
		code: 423,
		en: "White wine",
		nl: "Witte wijn",
		emoji: "🍷",
		category: "drinks",
		servings: [
			{
				en: "Glass (150 ml)",
				nl: "Glas (150 ml)",
				amount: 148,
				ml: 150,
				basis: "density",
				note: "wine 0.99 g/ml — alcohol is lighter than water",
			},
		],
	},

	// --------------------------------------------------------------- snacks --
	{
		code: 122,
		en: "Crisps",
		nl: "Chips",
		emoji: "🍟",
		category: "snacks",
		aliasEn: ["potato chips"],
		servings: [
			{ en: "Handful", nl: "Handje", amount: 25 },
			{ en: "Small bag", nl: "Klein zakje", amount: 40 },
		],
	},
	{
		code: 431,
		en: "Milk chocolate",
		nl: "Melkchocolade",
		emoji: "🍫",
		category: "snacks",
		aliasEn: ["chocolate"],
		aliasNl: ["chocolade"],
		servings: [
			{ en: "Two squares", nl: "Twee blokjes", amount: 10 },
			{ en: "Small bar", nl: "Klein reepje", amount: 45 },
		],
	},
	{
		code: 432,
		en: "Dark chocolate",
		nl: "Pure chocolade",
		emoji: "🍫",
		category: "snacks",
		servings: [{ en: "Two squares", nl: "Twee blokjes", amount: 10 }],
	},
	{
		code: 713,
		en: "Stroopwafel",
		nl: "Stroopwafel",
		emoji: "🧇",
		category: "snacks",
		aliasEn: ["syrup waffle"],
		servings: [{ en: "Waffle", nl: "Wafel", amount: 32 }],
	},
	{
		code: 261,
		en: "Speculaas biscuit",
		nl: "Speculaasje",
		emoji: "🍪",
		category: "snacks",
		aliasNl: ["speculaas"],
		servings: [
			{ en: "Biscuit", nl: "Koekje", amount: 6 },
			{ en: "Three biscuits", nl: "Drie koekjes", amount: 18 },
		],
	},
	{
		code: 240,
		en: "Dutch spiced cake",
		nl: "Ontbijtkoek",
		emoji: "🍰",
		category: "snacks",
		aliasNl: ["peperkoek", "snijkoek"],
		servings: [{ en: "Slice", nl: "Plak", amount: 25 }],
	},
	{
		code: 254,
		en: "Sponge cake",
		nl: "Eierkoek",
		emoji: "🍩",
		category: "snacks",
		servings: [{ en: "Cake", nl: "Eierkoek", amount: 45 }],
	},
	{
		code: 522,
		en: "Sweet liquorice",
		nl: "Zoete drop",
		emoji: "🍬",
		category: "snacks",
		aliasEn: ["liquorice"],
		aliasNl: ["drop"],
		servings: [{ en: "Handful", nl: "Handje", amount: 25 }],
	},
	{
		code: 520,
		en: "Salted liquorice",
		nl: "Zoute drop",
		emoji: "🍬",
		category: "snacks",
		servings: [{ en: "Handful", nl: "Handje", amount: 25 }],
	},
	{
		code: 5236,
		en: "Apple pie",
		nl: "Appeltaart",
		emoji: "🥧",
		category: "snacks",
		aliasNl: ["appelgebak"],
		servings: [{ en: "Slice", nl: "Punt", amount: 125 }],
	},
	{
		code: 5240,
		en: "Apple turnover",
		nl: "Appelflap",
		emoji: "🥧",
		category: "snacks",
		servings: [{ en: "Turnover", nl: "Appelflap", amount: 100 }],
	},
	{
		code: 255,
		en: "Cream cake",
		nl: "Slagroomtaart",
		emoji: "🎂",
		category: "snacks",
		aliasNl: ["slagroomgebak"],
		servings: [{ en: "Slice", nl: "Punt", amount: 100 }],
	},
	{
		code: 303,
		en: "Ice cream",
		nl: "Roomijs",
		emoji: "🍨",
		category: "snacks",
		aliasNl: ["vanille-ijs", "ijs"],
		servings: [
			{ en: "Scoop", nl: "Bolletje", amount: 50 },
			{ en: "Two scoops", nl: "Twee bolletjes", amount: 100 },
		],
	},
	{
		code: 2239,
		en: "Muesli bar",
		nl: "Mueslireep",
		emoji: "🍫",
		category: "snacks",
		aliasEn: ["cereal bar", "granola bar"],
		servings: [{ en: "Bar", nl: "Reep", amount: 25 }],
	},
	{
		code: 264,
		en: "Salted cracker",
		nl: "Zout koekje",
		emoji: "🍘",
		category: "snacks",
		aliasEn: ["cracker"],
		aliasNl: ["tuc"],
		servings: [
			{ en: "Cracker", nl: "Koekje", amount: 5 },
			{ en: "Handful", nl: "Handje", amount: 25 },
		],
	},
	{
		code: 322,
		en: "Frikandel",
		nl: "Frikandel",
		emoji: "🌭",
		category: "snacks",
		servings: [{ en: "Frikandel", nl: "Frikandel", amount: 80 }],
	},
	{
		code: 326,
		en: "Croquette",
		nl: "Kroket",
		emoji: "🥟",
		category: "snacks",
		servings: [{ en: "Croquette", nl: "Kroket", amount: 70 }],
	},
	{
		code: 943,
		en: "Bitterbal",
		nl: "Bitterbal",
		emoji: "🥟",
		category: "snacks",
		servings: [
			{ en: "Bitterbal", nl: "Bitterbal", amount: 20 },
			{ en: "Six pieces", nl: "Zes stuks", amount: 120 },
		],
	},

	// ---------------------------------------------------------------- meals --
	{
		code: 471,
		en: "Nasi goreng",
		nl: "Nasi goreng",
		emoji: "🍚",
		category: "meals",
		aliasEn: ["fried rice"],
		aliasNl: ["nasi"],
		servings: [{ en: "Plate", nl: "Bord", amount: 300 }],
	},
	{
		code: 470,
		en: "Bami goreng",
		nl: "Bami goreng",
		emoji: "🍜",
		category: "meals",
		aliasNl: ["bami"],
		servings: [{ en: "Plate", nl: "Bord", amount: 300 }],
	},
	{
		code: 1491,
		en: "Lasagne bolognese",
		nl: "Lasagne bolognese",
		emoji: "🍝",
		category: "meals",
		aliasEn: ["lasagna"],
		servings: [{ en: "Portion", nl: "Portie", amount: 400 }],
	},
	{
		code: 5432,
		en: "Pizza margherita",
		nl: "Pizza margherita",
		emoji: "🍕",
		category: "meals",
		aliasEn: ["pizza"],
		aliasNl: ["pizza"],
		servings: [
			{ en: "Slice", nl: "Punt", amount: 75 },
			{ en: "Whole pizza", nl: "Hele pizza", amount: 300 },
		],
	},
	{
		code: 1483,
		en: "Kale hotpot",
		nl: "Boerenkoolstamppot",
		emoji: "🥘",
		category: "meals",
		aliasEn: ["stamppot"],
		aliasNl: ["stamppot boerenkool"],
		servings: [{ en: "Plate", nl: "Bord", amount: 350 }],
	},
	{
		code: 1485,
		en: "Carrot and onion hotpot",
		nl: "Hutspot",
		emoji: "🥘",
		category: "meals",
		aliasEn: ["hotchpotch", "stamppot"],
		servings: [{ en: "Plate", nl: "Bord", amount: 350 }],
	},
	{
		code: 1486,
		en: "Sauerkraut hotpot",
		nl: "Zuurkoolstamppot",
		emoji: "🥘",
		category: "meals",
		aliasEn: ["stamppot"],
		servings: [{ en: "Plate", nl: "Bord", amount: 350 }],
	},
	{
		code: 865,
		en: "Chicken satay with peanut sauce",
		nl: "Kipsaté met satésaus",
		emoji: "🍢",
		category: "meals",
		aliasEn: ["satay"],
		aliasNl: ["sate"],
		servings: [{ en: "Portion", nl: "Portie", amount: 200 }],
	},
	{
		code: 766,
		en: "Pea soup with meat",
		nl: "Erwtensoep met vlees",
		emoji: "🍲",
		category: "meals",
		aliasNl: ["snert"],
		servings: [{ en: "Bowl", nl: "Kom", amount: 250 }],
	},
	{
		code: 800,
		en: "Vegetable soup",
		nl: "Groentesoep",
		emoji: "🍲",
		category: "meals",
		aliasEn: ["soup"],
		aliasNl: ["soep"],
		servings: [{ en: "Bowl", nl: "Kom", amount: 250 }],
	},
	{
		code: 5062,
		en: "Tomato soup",
		nl: "Tomatensoep",
		emoji: "🍲",
		category: "meals",
		servings: [{ en: "Bowl", nl: "Kom", amount: 250 }],
	},

	// ---------------------------------------------------------------- other --
	{
		code: 455,
		en: "Peanut butter",
		nl: "Pindakaas",
		emoji: "🥜",
		category: "other",
		servings: [
			{ en: "For a slice of bread", nl: "Op een boterham", amount: 15 },
			{ en: "Tablespoon", nl: "Eetlepel", amount: 20 },
		],
	},
	{
		code: 1311,
		en: "Chocolate sprinkles",
		nl: "Hagelslag",
		emoji: "🍫",
		category: "other",
		aliasEn: ["sprinkles"],
		servings: [
			{ en: "For a slice of bread", nl: "Op een boterham", amount: 12 },
		],
	},
	{
		code: 1964,
		en: "Chocolate spread",
		nl: "Chocoladepasta",
		emoji: "🍫",
		category: "other",
		aliasEn: ["hazelnut spread"],
		servings: [
			{ en: "For a slice of bread", nl: "Op een boterham", amount: 15 },
		],
	},
	{
		code: 2489,
		en: "Speculaas spread",
		nl: "Speculoospasta",
		emoji: "🍪",
		category: "other",
		servings: [
			{ en: "For a slice of bread", nl: "Op een boterham", amount: 15 },
		],
	},
	{
		code: 445,
		en: "Jam",
		nl: "Jam",
		emoji: "🍓",
		category: "other",
		aliasNl: ["confiture"],
		servings: [
			{ en: "For a slice of bread", nl: "Op een boterham", amount: 15 },
		],
	},
	{
		code: 443,
		en: "Honey",
		nl: "Honing",
		emoji: "🍯",
		category: "other",
		servings: [
			{ en: "Teaspoon", nl: "Theelepel", amount: 7 },
			{ en: "For a slice of bread", nl: "Op een boterham", amount: 15 },
		],
	},
	{
		code: 427,
		en: "Apple syrup",
		nl: "Appelstroop",
		emoji: "🍯",
		category: "other",
		servings: [
			{ en: "For a slice of bread", nl: "Op een boterham", amount: 15 },
		],
	},
	{
		code: 3207,
		en: "Hummus",
		nl: "Hummus",
		emoji: "🫓",
		category: "other",
		aliasNl: ["hoemoes"],
		servings: [{ en: "Portion", nl: "Portie", amount: 30 }],
	},
	{
		code: 462,
		en: "Tomato ketchup",
		nl: "Tomatenketchup",
		emoji: "🍅",
		category: "other",
		aliasEn: ["ketchup"],
		servings: [{ en: "Tablespoon", nl: "Eetlepel", amount: 15 }],
	},
	{
		code: 824,
		en: "Mustard",
		nl: "Mosterd",
		emoji: "🌭",
		category: "other",
		servings: [{ en: "Teaspoon", nl: "Theelepel", amount: 5 }],
	},
	{
		code: 616,
		en: "Peanut sauce",
		nl: "Satésaus",
		emoji: "🥜",
		category: "other",
		aliasNl: ["pindasaus"],
		servings: [{ en: "Portion", nl: "Portie", amount: 40 }],
	},
	{
		code: 1215,
		en: "Sweet soy sauce",
		nl: "Ketjap manis",
		emoji: "🍶",
		category: "other",
		aliasEn: ["ketjap"],
		servings: [{ en: "Tablespoon", nl: "Eetlepel", amount: 15 }],
	},
	{
		code: 377,
		en: "Sugar",
		nl: "Suiker",
		emoji: "🍚",
		category: "other",
		aliasNl: ["kristalsuiker", "tafelsuiker"],
		servings: [
			{ en: "Teaspoon", nl: "Theelepel", amount: 4 },
			{ en: "Sugar cube", nl: "Suikerklontje", amount: 4 },
		],
	},
	{
		code: 841,
		en: "Salt",
		nl: "Zout",
		emoji: "🧂",
		category: "other",
		servings: [{ en: "Pinch", nl: "Snufje", amount: 1 }],
	},
];
