import { mkdir, rm } from "node:fs/promises";
import { join } from "node:path";
import { readEnvValues, readProjectText, removeEnvNames, setEnvName, writeProjectText, } from "./dotenv.mjs";
import { deriveDeploymentReference } from "./identity.mjs";
import { workspaceExpiryAt } from "./policy.mjs";
export const DEPLOYMENT_ENV_NAMES = new Set([
    "CONVEX_DEPLOY_KEY",
    "CONVEX_DEPLOYMENT_TOKEN",
    "CONVEX_DEPLOYMENT",
    "VITE_CONVEX_URL",
    "CONVEX_URL",
    "CONVEX_SITE_URL",
    "NEXT_PUBLIC_CONVEX_URL",
    "EXPO_PUBLIC_CONVEX_URL",
]);
export const PROVIDER_ENV_REMOVALS = [...DEPLOYMENT_ENV_NAMES];
async function invoke(run, request) {
    const result = await run({
        tool: "convex",
        args: request.args,
        cwd: request.cwd,
        packageRoot: request.root,
        removeEnv: PROVIDER_ENV_REMOVALS,
    });
    if (result.status !== "ok")
        throw new Error(`${request.label} failed (${result.status})`);
    return result;
}
function requireOwnedEnvironment(text) {
    if (!text.startsWith("# Generated by @appelent/dev env apply ") &&
        !text.startsWith("# Generated by `pnpm run env:apply "))
        throw new Error("Workspace backend output requires an Appelent-generated root environment file");
}
export async function prepareBackend(request) {
    const { root, identity, policy, run } = request;
    if (policy.backend.mode === "none")
        return null;
    if (!policy.backend.project)
        throw new Error("Backend project is required for an isolated workspace");
    const fallback = await readProjectText(root, ".env");
    if (removeEnvNames(fallback, DEPLOYMENT_ENV_NAMES) !== fallback)
        throw new Error("Workspace backend setup refuses deployment selectors in .env; remove them before preparing");
    let rootEnv = await readProjectText(root, policy.outputs.rootEnv);
    requireOwnedEnvironment(rootEnv);
    rootEnv = removeEnvNames(rootEnv, DEPLOYMENT_ENV_NAMES);
    await writeProjectText(root, policy.outputs.rootEnv, rootEnv);
    const staging = policy.backend.mode === "local"
        ? root
        : join(request.isolationRoot, "provider");
    if (policy.backend.mode !== "local") {
        await rm(staging, { recursive: true, force: true });
        await mkdir(staging, { recursive: true });
    }
    try {
        const reference = policy.backend.mode === "cloud"
            ? `${policy.backend.project}:${deriveDeploymentReference(identity, request.editor)}`
            : `${policy.backend.project}:local`;
        const select = await run({
            tool: "convex",
            args: ["deployment", "select", reference],
            cwd: staging,
            packageRoot: root,
            removeEnv: PROVIDER_ENV_REMOVALS,
        });
        let created = false;
        if (select.status === "not-found") {
            await request.checkpoint({
                kind: "convex-deployment",
                id: reference,
                owned: true,
                status: "retained",
                cleanup: policy.backend.mode === "cloud" ? "expiry" : "release",
                expiresAt: policy.backend.mode === "cloud"
                    ? (workspaceExpiryAt(policy.backend.expiration, request.now) ??
                        undefined)
                    : undefined,
                metadata: {
                    mode: policy.backend.mode,
                    expiration: policy.backend.expiration,
                },
            });
            const args = policy.backend.mode === "cloud"
                ? [
                    "deployment",
                    "create",
                    reference,
                    "--select",
                    "--type",
                    "dev",
                    "--expiration",
                    policy.backend.expiration,
                ]
                : ["deployment", "create", reference, "--select"];
            await invoke(run, {
                root,
                cwd: staging,
                args,
                label: "Backend creation",
            });
            created = true;
            await request.checkpoint({
                kind: "convex-deployment",
                id: reference,
                owned: true,
                status: "active",
                cleanup: policy.backend.mode === "cloud" ? "expiry" : "release",
                expiresAt: policy.backend.mode === "cloud"
                    ? (workspaceExpiryAt(policy.backend.expiration, request.now) ??
                        undefined)
                    : undefined,
                metadata: {
                    mode: policy.backend.mode,
                    expiration: policy.backend.expiration,
                },
            });
        }
        else if (select.status !== "ok") {
            throw new Error(`Backend lookup failed (${select.status}); refusing to create`);
        }
        const selected = readEnvValues(await readProjectText(staging, ".env.local"));
        const publicUrl = selected.VITE_CONVEX_URL ?? selected.CONVEX_URL;
        const deploymentName = selected.CONVEX_DEPLOYMENT;
        if (!publicUrl || !deploymentName)
            throw new Error("Selected backend did not provide client outputs");
        let publicHostname;
        try {
            publicHostname = new URL(publicUrl).hostname;
        }
        catch {
            throw new Error("Selected backend wrote an invalid client URL");
        }
        for (const name of [
            "CONVEX_DEPLOYMENT",
            "VITE_CONVEX_URL",
            "CONVEX_URL",
            "CONVEX_SITE_URL",
        ])
            if (selected[name] !== undefined)
                rootEnv = setEnvName(rootEnv, name, selected[name] ?? "");
        await writeProjectText(root, policy.outputs.rootEnv, rootEnv);
        const resource = {
            kind: "convex-deployment",
            id: reference,
            owned: created || request.existing?.owned === true,
            status: "active",
            cleanup: policy.backend.mode === "cloud" ? "expiry" : "release",
            expiresAt: request.existing?.expiresAt ??
                (policy.backend.mode === "cloud"
                    ? (workspaceExpiryAt(policy.backend.expiration, request.now) ??
                        undefined)
                    : undefined),
            metadata: {
                mode: policy.backend.mode,
                deploymentName,
                expiration: policy.backend.expiration,
            },
        };
        await request.checkpoint(resource);
        return {
            reference,
            publicUrl,
            publicHostname,
            resource,
            operation: {
                action: created ? "write" : "reuse",
                target: `convex:${reference}`,
                detail: created
                    ? "created isolated backend"
                    : "selected existing backend",
            },
        };
    }
    finally {
        if (policy.backend.mode === "cloud")
            await rm(staging, { recursive: true, force: true }).catch(() => undefined);
    }
}
export async function createScopedCredential(request) {
    const staging = join(request.isolationRoot, "provider-token");
    await rm(staging, { recursive: true, force: true });
    await mkdir(staging, { recursive: true });
    try {
        const tokenName = `appelent-${request.identity.id}`;
        const resource = {
            kind: "convex-token",
            id: tokenName,
            owned: true,
            status: "retained",
            cleanup: "delete",
            metadata: { deployment: request.reference },
        };
        await request.checkpoint(resource);
        const result = await invoke(request.run, {
            root: request.root,
            cwd: staging,
            args: [
                "deployment",
                "token",
                "create",
                tokenName,
                "--deployment",
                request.reference,
            ],
            label: "Scoped credential creation",
        });
        const token = /(?:^|\n)((?:dev|prod|preview):[^|\r\n]+\|[^\s\r\n]+)(?:\r?\n|$)/u.exec(result.stdout)?.[1];
        if (!token)
            throw new Error("Scoped credential was created but its value was not captured");
        resource.status = "active";
        await request.checkpoint(resource);
        const current = await readProjectText(request.root, request.policy.outputs.rootEnv);
        requireOwnedEnvironment(current);
        await writeProjectText(request.root, request.policy.outputs.rootEnv, setEnvName(current, "CONVEX_DEPLOY_KEY", token));
        return {
            resource,
            operation: {
                action: "write",
                target: `convex-token:${tokenName}`,
                detail: "created scoped credential",
            },
        };
    }
    finally {
        await rm(staging, { recursive: true, force: true }).catch(() => undefined);
    }
}
export async function pushBackend(root, policy, run) {
    const values = readEnvValues(await readProjectText(root, policy.outputs.rootEnv));
    const key = values.CONVEX_DEPLOY_KEY;
    const selected = values.CONVEX_DEPLOYMENT;
    if (!key || !selected || !key.startsWith(`${selected}|`))
        throw new Error("Scoped credential does not match the selected backend");
    await invoke(run, {
        root,
        cwd: root,
        args: ["dev", "--once", "--env-file", policy.outputs.rootEnv],
        label: "Backend push",
    });
}
export async function writeClientOutputs(root, policy, publicUrl) {
    if (!publicUrl || !policy.outputs.mobileEnv)
        return [];
    const current = await readProjectText(root, policy.outputs.mobileEnv);
    if (current &&
        !current.startsWith("# Generated by @appelent/dev env apply ") &&
        !current.startsWith("# Generated by `pnpm run env:apply "))
        throw new Error("Workspace mobile output requires an Appelent-generated environment file");
    await writeProjectText(root, policy.outputs.mobileEnv, setEnvName(current, policy.outputs.mobileUrlName, publicUrl));
    return [
        {
            action: "write",
            target: policy.outputs.mobileEnv,
            detail: `${policy.outputs.mobileUrlName} follows selected backend`,
        },
    ];
}
export async function cleanupProviderResource(packageRoot, isolationRoot, resource, run, now = new Date()) {
    if (!resource.owned ||
        resource.status === "removed" ||
        resource.status === "absent")
        return resource;
    if (resource.kind === "convex-token") {
        const deployment = String(resource.metadata?.deployment ?? "");
        if (!deployment)
            return { ...resource, status: "inaccessible" };
        await mkdir(isolationRoot, { recursive: true });
        const result = await run({
            tool: "convex",
            args: [
                "deployment",
                "token",
                "delete",
                resource.id,
                "--deployment",
                deployment,
            ],
            cwd: isolationRoot,
            packageRoot,
            removeEnv: PROVIDER_ENV_REMOVALS,
        });
        if (result.status === "ok" || result.status === "not-found")
            return {
                ...resource,
                status: result.status === "ok" ? "removed" : "absent",
            };
        return { ...resource, status: "inaccessible" };
    }
    if (resource.kind === "convex-deployment") {
        if (resource.cleanup !== "expiry")
            return { ...resource, status: "retained" };
        if (!resource.expiresAt ||
            new Date(resource.expiresAt).getTime() > now.getTime())
            return { ...resource, status: "pending-expiry" };
        await rm(isolationRoot, { recursive: true, force: true });
        await mkdir(isolationRoot, { recursive: true });
        const result = await run({
            tool: "convex",
            args: ["deployment", "select", resource.id],
            cwd: isolationRoot,
            packageRoot,
            removeEnv: PROVIDER_ENV_REMOVALS,
        });
        if (result.status === "not-found")
            return { ...resource, status: "absent" };
        if (result.status === "ok")
            return { ...resource, status: "pending-expiry" };
        return { ...resource, status: "inaccessible" };
    }
    if (resource.kind === "port")
        return { ...resource, status: "removed" };
    if (resource.kind === "process") {
        const pid = Number(resource.metadata?.pid);
        if (!Number.isSafeInteger(pid) || pid <= 0)
            return { ...resource, status: "inaccessible" };
        try {
            process.kill(pid, 0);
            return { ...resource, status: "inaccessible" };
        }
        catch (error) {
            return error.code === "ESRCH"
                ? { ...resource, status: "absent" }
                : { ...resource, status: "inaccessible" };
        }
    }
    return resource;
}
