import type { Locale } from "../i18n";

const en = {
	history: "Activity history",
	all: "All",
	strength: "Strength",
	running: "Running",
	cycling: "Cycling",
	run: "Run",
	ride: "Ride",
	session: "Strength session",
	logRun: "Log run",
	logRide: "Log ride",
	logActivity: "Log activity",
	startActivity: "Start activity",
	recent: "Recent activities",
	seeAll: "See all",
	thisWeek: "This week",
	activities: "Activities",
	distance: "Distance",
	duration: "Duration",
	pace: "Average pace",
	speed: "Average speed",
	loading: "Loading activities",
	emptyTitle: "No activities yet",
	emptyBody: "Log a run or ride, or finish a strength session to see it here.",
	filteredEmpty: "Your completed activities for this sport will appear here.",
	loadMore: "Load more",
	errorTitle: "Activities could not be loaded",
	errorBody: "Check your connection and try again.",
	retry: "Try again",
	weeklyDistance: "Weekly distance (km)",
	weeklyDuration: "Weekly duration (minutes)",
	previousWeek: "Previous week",
	nextWeek: "Next week",
	weekEmpty: "No activities this week",
	weekEmptyBody: "Choose another week or log an activity.",
	ready: "Ready to move",
	resume: "Resume",
	inProgress: "In progress",
	logBody: "Record a completed run or ride, or start a strength session.",
	exercises: "Exercises",
	body: "Body",
	volume: "Every set type, warmups included.",
};
const nl: typeof en = {
	history: "Activiteitengeschiedenis",
	all: "Alles",
	strength: "Kracht",
	running: "Hardlopen",
	cycling: "Fietsen",
	run: "Hardloopsessie",
	ride: "Fietsrit",
	session: "Krachtsessie",
	logRun: "Hardloopsessie vastleggen",
	logRide: "Fietsrit vastleggen",
	logActivity: "Activiteit vastleggen",
	startActivity: "Activiteit starten",
	recent: "Recente activiteiten",
	seeAll: "Alles bekijken",
	thisWeek: "Deze week",
	activities: "Activiteiten",
	distance: "Afstand",
	duration: "Duur",
	pace: "Gemiddeld tempo",
	speed: "Gemiddelde snelheid",
	loading: "Activiteiten laden",
	emptyTitle: "Nog geen activiteiten",
	emptyBody:
		"Leg een hardloopsessie of fietsrit vast, of rond een krachtsessie af om die hier te zien.",
	filteredEmpty: "Je afgeronde activiteiten voor deze sport verschijnen hier.",
	loadMore: "Meer laden",
	errorTitle: "Activiteiten konden niet worden geladen",
	errorBody: "Controleer je verbinding en probeer het opnieuw.",
	retry: "Opnieuw proberen",
	weeklyDistance: "Wekelijkse afstand (km)",
	weeklyDuration: "Wekelijkse duur (minuten)",
	previousWeek: "Vorige week",
	nextWeek: "Volgende week",
	weekEmpty: "Geen activiteiten deze week",
	weekEmptyBody: "Kies een andere week of leg een activiteit vast.",
	ready: "Klaar om te bewegen",
	resume: "Doorgaan",
	inProgress: "Bezig",
	logBody:
		"Leg een afgeronde hardloopsessie of fietsrit vast, of start een krachtsessie.",
	exercises: "Oefeningen",
	body: "Lichaam",
	volume: "Alle soorten sets, inclusief opwarming.",
};
export const activityCopy = (locale: Locale) => (locale === "nl" ? nl : en);
