import type { Locale } from "../i18n";

export const enduranceCopy = {
	en: {
		running: "Run",
		cycling: "Ride",
		logRun: "Log run",
		logRide: "Log ride",
		editRun: "Edit run",
		editRide: "Edit ride",
		date: "Date",
		time: "Time",
		distance: "Distance",
		duration: "Duration",
		hours: "Hours",
		minutes: "Minutes",
		seconds: "Seconds",
		title: "Title",
		notes: "Notes",
		moreDetails: "More details",
		environment: "Location",
		outdoor: "Outdoor",
		indoor: "Indoor",
		unspecified: "Not set",
		elevation: "Elevation gain",
		heartRate: "Average heart rate",
		effort: "Effort",
		pace: "Average pace",
		speed: "Average speed",
		save: "Save activity",
		saving: "Saving…",
		edit: "Edit",
		delete: "Delete",
		keepActivity: "Keep activity",
		deleting: "Deleting…",
		deleteRun: "Delete run",
		deleteRide: "Delete ride",
		deleteTitle: "Delete this activity?",
		deleteMessage: "This activity will be removed from your history.",
		discardTitle: "Discard changes?",
		discardMessage: "Your changes have not been saved.",
		discard: "Discard changes",
		keepEditing: "Keep editing",
		invalidDate: "Enter a valid date and time.",
		invalidDistance: "Enter a distance greater than zero.",
		invalidDuration: "Enter a duration greater than zero.",
		invalidElevation: "Elevation gain must be zero or greater.",
		invalidHeartRate: "Enter a whole-number heart rate greater than zero.",
		invalidEffort: "Effort must be a whole number from 1 to 10.",
		invalidTitle: "Title must be 200 characters or fewer.",
		invalidNotes: "Notes must be 10,000 characters or fewer.",
		saveError: "Could not save the activity.",
		deleteError: "Could not delete the activity.",
		missing: "Activity not found",
		missingBody: "It may have been deleted, or you may no longer have access.",
		loading: "Loading activity",
		details: "Details",
		dateHint: "YYYY-MM-DD",
		today: "Today",
		done: "Done",
		close: "Close date picker",
		offlineError: "Connect to save this activity. Your input is still here.",
		offlineDeleteError: "Connect to delete this activity.",
		offlineTitle: "Activity unavailable offline",
		offlineBody: "Connect to load this activity, then try again.",
		retry: "Try again",
		timeHint: "HH:mm",
	},
	nl: {
		running: "Hardloopsessie",
		cycling: "Fietstocht",
		logRun: "Hardlooptraining loggen",
		logRide: "Fietstocht loggen",
		editRun: "Hardloopsessie bewerken",
		editRide: "Fietstocht bewerken",
		date: "Datum",
		time: "Tijd",
		distance: "Afstand",
		duration: "Duur",
		hours: "Uren",
		minutes: "Minuten",
		seconds: "Seconden",
		title: "Titel",
		notes: "Notities",
		moreDetails: "Meer details",
		environment: "Locatie",
		outdoor: "Buiten",
		indoor: "Binnen",
		unspecified: "Niet ingesteld",
		elevation: "Hoogtemeters",
		heartRate: "Gemiddelde hartslag",
		effort: "Inspanning",
		pace: "Gemiddeld tempo",
		speed: "Gemiddelde snelheid",
		save: "Activiteit opslaan",
		saving: "Opslaan…",
		edit: "Bewerken",
		delete: "Verwijderen",
		keepActivity: "Activiteit behouden",
		deleting: "Verwijderen…",
		deleteRun: "Hardloopsessie verwijderen",
		deleteRide: "Fietstocht verwijderen",
		deleteTitle: "Deze activiteit verwijderen?",
		deleteMessage: "Deze activiteit verdwijnt uit je geschiedenis.",
		discardTitle: "Wijzigingen weggooien?",
		discardMessage: "Je wijzigingen zijn nog niet opgeslagen.",
		discard: "Wijzigingen weggooien",
		keepEditing: "Verder bewerken",
		invalidDate: "Vul een geldige datum en tijd in.",
		invalidDistance: "Vul een afstand groter dan nul in.",
		invalidDuration: "Vul een duur groter dan nul in.",
		invalidElevation: "Hoogtemeters moeten nul of hoger zijn.",
		invalidHeartRate: "Vul een positieve hartslag in als geheel getal.",
		invalidEffort: "Inspanning moet een geheel getal van 1 tot 10 zijn.",
		invalidTitle: "De titel mag maximaal 200 tekens bevatten.",
		invalidNotes: "Notities mogen maximaal 10.000 tekens bevatten.",
		saveError: "Activiteit opslaan is mislukt.",
		deleteError: "Activiteit verwijderen is mislukt.",
		missing: "Activiteit niet gevonden",
		missingBody:
			"De activiteit is mogelijk verwijderd of niet meer beschikbaar.",
		loading: "Activiteit laden",
		details: "Details",
		dateHint: "JJJJ-MM-DD",
		today: "Vandaag",
		done: "Gereed",
		close: "Datumkiezer sluiten",
		offlineError:
			"Maak verbinding om deze activiteit op te slaan. Je invoer staat er nog.",
		offlineDeleteError: "Maak verbinding om deze activiteit te verwijderen.",
		offlineTitle: "Activiteit offline niet beschikbaar",
		offlineBody:
			"Maak verbinding om deze activiteit te laden en probeer het opnieuw.",
		retry: "Opnieuw proberen",
		timeHint: "UU:mm",
	},
} satisfies Record<Locale, Record<string, string>>;

export type EnduranceCopy = (typeof enduranceCopy)["en"];
