/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WodsIndexRouteImport } from './routes/wods/index'
import { Route as RoutinesIndexRouteImport } from './routes/routines/index'
import { Route as ProgressIndexRouteImport } from './routes/progress/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LogIndexRouteImport } from './routes/log/index'
import { Route as HostedWorkoutsIndexRouteImport } from './routes/hosted-workouts/index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as WodsIdRouteImport } from './routes/wods/$id'
import { Route as LogSessionIdRouteImport } from './routes/log/$sessionId'
import { Route as HostedWorkoutsNewRouteImport } from './routes/hosted-workouts/new'
import { Route as ExercisesIdRouteImport } from './routes/exercises/$id'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WodsIndexRoute = WodsIndexRouteImport.update({
  id: '/wods/',
  path: '/wods/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesIndexRoute = RoutinesIndexRouteImport.update({
  id: '/routines/',
  path: '/routines/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressIndexRoute = ProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogIndexRoute = LogIndexRouteImport.update({
  id: '/log/',
  path: '/log/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedWorkoutsIndexRoute = HostedWorkoutsIndexRouteImport.update({
  id: '/hosted-workouts/',
  path: '/hosted-workouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const WodsIdRoute = WodsIdRouteImport.update({
  id: '/wods/$id',
  path: '/wods/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LogSessionIdRoute = LogSessionIdRouteImport.update({
  id: '/log/$sessionId',
  path: '/log/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedWorkoutsNewRoute = HostedWorkoutsNewRouteImport.update({
  id: '/hosted-workouts/new',
  path: '/hosted-workouts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIdRoute = ExercisesIdRouteImport.update({
  id: '/exercises/$id',
  path: '/exercises/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/hosted-workouts/new': typeof HostedWorkoutsNewRoute
  '/log/$sessionId': typeof LogSessionIdRoute
  '/wods/$id': typeof WodsIdRoute
  '/account/': typeof AccountIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/hosted-workouts/': typeof HostedWorkoutsIndexRoute
  '/log/': typeof LogIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/progress/': typeof ProgressIndexRoute
  '/routines/': typeof RoutinesIndexRoute
  '/wods/': typeof WodsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/hosted-workouts/new': typeof HostedWorkoutsNewRoute
  '/log/$sessionId': typeof LogSessionIdRoute
  '/wods/$id': typeof WodsIdRoute
  '/account': typeof AccountIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/exercises': typeof ExercisesIndexRoute
  '/hosted-workouts': typeof HostedWorkoutsIndexRoute
  '/log': typeof LogIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/progress': typeof ProgressIndexRoute
  '/routines': typeof RoutinesIndexRoute
  '/wods': typeof WodsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/hosted-workouts/new': typeof HostedWorkoutsNewRoute
  '/log/$sessionId': typeof LogSessionIdRoute
  '/wods/$id': typeof WodsIdRoute
  '/account/': typeof AccountIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/hosted-workouts/': typeof HostedWorkoutsIndexRoute
  '/log/': typeof LogIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/progress/': typeof ProgressIndexRoute
  '/routines/': typeof RoutinesIndexRoute
  '/wods/': typeof WodsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/exercises/$id'
    | '/hosted-workouts/new'
    | '/log/$sessionId'
    | '/wods/$id'
    | '/account/'
    | '/dashboard/'
    | '/exercises/'
    | '/hosted-workouts/'
    | '/log/'
    | '/login/'
    | '/profile/'
    | '/progress/'
    | '/routines/'
    | '/wods/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/exercises/$id'
    | '/hosted-workouts/new'
    | '/log/$sessionId'
    | '/wods/$id'
    | '/account'
    | '/dashboard'
    | '/exercises'
    | '/hosted-workouts'
    | '/log'
    | '/login'
    | '/profile'
    | '/progress'
    | '/routines'
    | '/wods'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/exercises/$id'
    | '/hosted-workouts/new'
    | '/log/$sessionId'
    | '/wods/$id'
    | '/account/'
    | '/dashboard/'
    | '/exercises/'
    | '/hosted-workouts/'
    | '/log/'
    | '/login/'
    | '/profile/'
    | '/progress/'
    | '/routines/'
    | '/wods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ExercisesIdRoute: typeof ExercisesIdRoute
  HostedWorkoutsNewRoute: typeof HostedWorkoutsNewRoute
  LogSessionIdRoute: typeof LogSessionIdRoute
  WodsIdRoute: typeof WodsIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  HostedWorkoutsIndexRoute: typeof HostedWorkoutsIndexRoute
  LogIndexRoute: typeof LogIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProgressIndexRoute: typeof ProgressIndexRoute
  RoutinesIndexRoute: typeof RoutinesIndexRoute
  WodsIndexRoute: typeof WodsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wods/': {
      id: '/wods/'
      path: '/wods'
      fullPath: '/wods/'
      preLoaderRoute: typeof WodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/': {
      id: '/routines/'
      path: '/routines'
      fullPath: '/routines/'
      preLoaderRoute: typeof RoutinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/': {
      id: '/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof ProgressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log/': {
      id: '/log/'
      path: '/log'
      fullPath: '/log/'
      preLoaderRoute: typeof LogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted-workouts/': {
      id: '/hosted-workouts/'
      path: '/hosted-workouts'
      fullPath: '/hosted-workouts/'
      preLoaderRoute: typeof HostedWorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wods/$id': {
      id: '/wods/$id'
      path: '/wods/$id'
      fullPath: '/wods/$id'
      preLoaderRoute: typeof WodsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log/$sessionId': {
      id: '/log/$sessionId'
      path: '/log/$sessionId'
      fullPath: '/log/$sessionId'
      preLoaderRoute: typeof LogSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted-workouts/new': {
      id: '/hosted-workouts/new'
      path: '/hosted-workouts/new'
      fullPath: '/hosted-workouts/new'
      preLoaderRoute: typeof HostedWorkoutsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$id': {
      id: '/exercises/$id'
      path: '/exercises/$id'
      fullPath: '/exercises/$id'
      preLoaderRoute: typeof ExercisesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ExercisesIdRoute: ExercisesIdRoute,
  HostedWorkoutsNewRoute: HostedWorkoutsNewRoute,
  LogSessionIdRoute: LogSessionIdRoute,
  WodsIdRoute: WodsIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  HostedWorkoutsIndexRoute: HostedWorkoutsIndexRoute,
  LogIndexRoute: LogIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProgressIndexRoute: ProgressIndexRoute,
  RoutinesIndexRoute: RoutinesIndexRoute,
  WodsIndexRoute: WodsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
